### ISSUE TITLE
Memory-Undertale by Toby Fox

### ISSUE THREAD

**Issue by tommieboye** [Externalizable/bongo.cat#10]
Memory-Undertale

1 8 6 1 5 5 6 1 8 1 5 5 6 5 6 0 8 6 8

**Comment by Kamjue** [comment]
1 8 6 1 5 5 6 1 6 1 5 5 6 1 8 6 1 5 5 6 1 6 0 8 6 8
This one is longer **;3**

**Comment by MagmasDemise06** [comment]
This one seems more accurate
3-0-8-3-7-7-8
3-8-3-7-7-8
3-0-8-7-7-8
1-6-0-8-6-8

**Comment by imanub211** [comment]
i think this is a little better

2 9 7 2 6 6 7 2 7 2 6 6 7 2 9 7 2 6 6 7 2 6 6 7 2 7 1 9 7 9

**Comment by Lajik1** [comment]
or qqyq tty, qyq tty, qiyq tty, qyp iyi
