### ISSUE TITLE
super mario bros 

### ISSUE THREAD

**Issue by ALEXANDRU2233** [Externalizable/bongo.cat#14]
8 8 8 1 8 0 1 7 6 5 6 7 6 5

**Comment by Externalizable** [comment]
I'm having issues hearing the theme from the get-go but it has a nice ring to it - thank you for the submission!

**Comment by grondonanicolas** [comment]
Hi @Externalizable, i think that this could work for Mario Song T T T Q T I E P T Q I P O I Q T I P Y I T . I have an issue with the next 3 notes because there is no B in the keyboard. Maybe with the refactor suggested by guastallaigor  i could finish it
