### ISSUE TITLE
This website breaks the conditions of .CAT domains

### ISSUE THREAD

**Issue by mrcasals** [Externalizable/bongo.cat#144]
Hi!

Just as a heads-up, this website might be breaking the conditions to use the `.cat` domains. As explained in the official FAQS of the domain (https://domini.cat/en/faqs/):

![image](https://user-images.githubusercontent.com/491891/96986043-60f97f80-1521-11eb-931b-ac467447cbd7.png)

> The .cat domain is a cultural and linguistic domain that belongs to the whole of the Catalan-speaking community and to whoever wants to use it. The only requirement is for the website to have a significant amount of contents in Catalan. Any person, organisation or company, whether or not it is located in Catalonia, can register a .cat if its site is includes a minimum amount of contents in Catalan.

This requirement is shown at every domain registrar when buying the domain (although the registrar you used could certainly have a better UI for this kind of messages...).

In order to fulfill this, you'd need to offer a Catalan version of the website (just translating the texts is enough, you can use Google Translate for this, since it's pretty accurate)

**Comment by sabbyX** [comment]
CatLivesMatter

**Comment by rhaps0dy** [comment]
I'm happy to make a translation pull request too -- there's not that much wordy material in the site. Some lightweight javascript should be able to switch the en<->cat language selection.

**Comment by Externalizable** [comment]
> I'm happy to make a translation pull request too -- there's not that much wordy material in the site. Some lightweight javascript should be able to switch the en<->cat language selection.

Awesome! Looking forward to it.

The option to translate the page could go somewhere in the footer block.

**Comment by mrcasals** [comment]
Yay, thanks @rhaps0dy! 😄
