### ISSUE TITLE
Lose Yourself - Eminem

### ISSUE THREAD

**Issue by Guinome** [Externalizable/bongo.cat#153]
**Lose Yourself - Eminem**

Chords (press simultaneously):
```
Piano
50 50 50 50
50 50 50 50
60 60 60 60
30 30 30 30

or Marimba
tp tp tp tp
tp tp tp tp
yp yp yp yp
ep ep ep ep
```

**Comment by rafiuske** [comment]
Intro
0 8 6 0 9 7 5
9 0 8 6

5 4 0 9

0 8 6 0 9 7 5
9 0 8 6

6 4 2 6 5
4 3 2
3 4 6 1 7 1 2

Listen here:
https://twitter.com/rafiuske/status/1333970240078835712?s=19
