### ISSUE TITLE
Oggy and the Cockroaches Theme Song

### ISSUE THREAD

**Issue by HoneyBon** [Externalizable/bongo.cat#23]
4 5 6 5
4 5 6 5
4 5 6 7 8
4 5 6 5
4 5 6 5
4 5 6 8 9

**Comment by SeveViola** [comment]
You can use the Piano or Marimba:
Piano: 1-2-3-2-1-2-3-2-1-2-3-4-5
Marimba: q-w-e-w-q-w-e-w-q-w-e-r-t
Both of them are the same but different sounds (I like the Marimba)
