### ISSUE TITLE
No Sounds

### ISSUE THREAD

**Issue by JediThePro** [Externalizable/bongo.cat#237]
Hi,
I forked the entire code but when I running the code in html, there'$ no sound. I see things normally. But when i trying to play sounds, there's no sounds. Any help?

@Externalizable

**Comment by Externalizable** [comment]
You're probably running into the same [CORS policy violation](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) as the user in #93.

Modern browsers prevent loading files from hard drives for security reasons. The files are loaded here: https://github.com/Externalizable/bongo.cat/blob/master/js/core.js#L155-L181

Try running the code on a locally hosted server, like [WAMP](https://www.wampserver.com/en/).
