### ISSUE TITLE
Bongocat is crashed and couldn't find any solutions.

### ISSUE THREAD

**Issue by bbb5vz** [Externalizable/bongo.cat#316]
![1](https://user-images.githubusercontent.com/86833568/124267643-7f654f80-db73-11eb-9b50-e9028318432a.JPG)

I just download obs and bongocat file and this happened. (nothing else)

Quite surprised that no one ever had an issue like this.

Is there any advice or solution for my problem?

**Comment by Externalizable** [comment]
Hey, this is the repository for the bongo.cat website. I think you might be referring to one of the Bongo Cat OBS plugins for which I cannot provide support here. I suggest you get in touch with the author of the OBS plugin you downloaded. Good luck!
