### ISSUE TITLE
Translate - ES

### ISSUE THREAD

**Issue by Hugii-20** [Externalizable/bongo.cat#367]
Hello! i recreated the web to only translate it to spanish instead of catalá, how i can do it?

**Comment by Externalizable** [comment]
The code for translations is located here: https://github.com/Externalizable/bongo.cat/blob/master/js/core.js#L292-L380
Check out the related Pull Request for more details: #151

Feel free to publish your Spanish translation [according to the licensing agreement](https://github.com/Externalizable/bongo.cat/blob/master/LICENSE), but I should note that there are no plans to translate the bongo.cat website right now, so I won't be merging in any new translation Pull Requests at this time. Happy coding!
