### ISSUE TITLE
[Song Submission] All Star

### ISSUE THREAD

**Issue by ButtonButt** [Externalizable/bongo.cat#40]
2 9 66 44 2 7 66 44 2 29 66 44 22 (Songthing lower)

**Comment by ButtonButt** [comment]
Check Out My YT Channel 
ButtonButt 
https://www.youtube.com/channel/UCVJskZIyR7LXmKptif5_LyA?view_as=subscriber

**Comment by Kamjue** [comment]
I think it's better to repeat the second "2" twice
Like this:

- **2 9 66 44 22 7 66 44 2 29 66 44 22**
