### ISSUE TITLE
pirates of the caribean

### ISSUE THREAD

**Issue by bloogalaxypro** [Externalizable/bongo.cat#41]
333566656563

**Comment by kerbalnaut** [comment]
> 333566656563
here is another one 11 33 5 66 8 66 53

**Comment by kerbalnaut** [comment]
here is another one 
(first verse) 1 33 5 66 8 66 53
(second verse) 11 33 5 66 56 313

**Comment by conartist6** [comment]
Wouldn't that be 3335666511113

**Comment by coolnirdh** [comment]
Try this instead: 
33 3566 6855 3113
33 3566 6855 313
33 3688 80 and then you need higher notes 😓
