### ISSUE TITLE
Gravity Falls Song

### ISSUE THREAD

**Issue by Lord4ngel** [Externalizable/bongo.cat#42]
03 56 0801 3 565 8086
6660086 0008086 6660086

**Comment by treewolves** [comment]
I played this and it sounds amazing

**Comment by Lord4ngel** [comment]
thanks

**Comment by Winter76Bongo** [comment]
when playing try this
03-56-0801-3-565-8086-6660086-0008086-6660086-666000

**Comment by jes09** [comment]
For the > 03-56-0801-3-565-8086-6660086-0008086-6660086-666000 try it without the 666000
