### ISSUE TITLE
'503 service temporarily unavailable'

### ISSUE THREAD

**Issue by heatherxoxx** [Externalizable/bongo.cat#460]
hello! i am a huge fan of bongo cat and i like to play on it everyday. however, most days that i try to go on it, it comes up with '503 service temporarily unavailable' with 'cloudflare' underneath it. this comes up more than the actual website, meaning that i can't go on bongo cat.
![Screenshot (3459)](https://user-images.githubusercontent.com/121464983/209588155-4f661bbe-830b-4019-a3bf-dcb3ad32f469.png)

**Comment by Externalizable** [comment]
Hey @heatherxoxx,

That's really odd, I don't see any errors on my side.

Next time you (or anyone else) encounter a `503 Service Temporarily Unavailable` error, could you visit [bongo.cat/cdn-cgi/trace](https://bongo.cat/cdn-cgi/trace) and email me the output to `trace@bongo.cat`? Please **do not** post it as a response to this GitHub issue–the output contains your IP address, which could be used to identify you!

I appreciate your help! :-)

**Comment by Externalizable** [comment]
I just deployed a slight change to the caching engine and purged the site cache; it's possible this will fix the errors but I have no way of knowing until the error pops up again

**Comment by heatherxoxx** [comment]
> Hey @heatherxoxx,
> 
> That's really odd, I don't see any errors on my side.
> 
> Next time you (or anyone else) encounter a `503 Service Temporarily Unavailable` error, could you visit [bongo.cat/cdn-cgi/trace](https://bongo.cat/cdn-cgi/trace) and email me the output to `trace@bongo.cat`? Please **do not** post it as a response to this GitHub issue–the output contains your IP address, which could be used to identify you!
> 
> I appreciate your help! :-)

thank you so much :) bongo cat is working whenever i want it to now, but if it does happen again i will let you know and visit the other website
