### ISSUE TITLE
Page not loading (Browser)

### ISSUE THREAD

**Issue by hwcodes** [Externalizable/bongo.cat#495]
if you go to the website on any standard browser the page is blank and only the ico loads. I've tried on 4 devices, I got the same results. 

![Screenshot 2024-02-14 8 52 16 AM](https://github.com/Externalizable/bongo.cat/assets/155579814/15f565b8-7df6-425e-ba1d-979a668c9e95)

**Comment by hwcodes** [comment]
Fixed

**Comment by TryingNormal42** [comment]
Fixed how? I've been getting this same screen on my mobile device for weeks now
