### ISSUE TITLE
Chopsticks

### ISSUE THREAD

**Issue by djdevin** [Externalizable/bongo.cat#53]
2+4 (x6)
1+4 (x6)
1+8 1+8 1+8 1+8 1+6 1+8 1+9
1+9 1+9 1+8 1+6
2+4 (x6)
1+4 (x6)
1+8 1+8 1+8 1+8 1+6 1+8 19191919191919

**Comment by cclarkson** [comment]
Ummmmm well actually.......
2+4 (x6)
1+4 (x6)
2+8 2+8 2+8 2+8 2+6 2+8 
1+9 1+9 1+9 1+9 1+8 1+6
2+4 (x6)
1+4 (x6)
2+8 2+8 2+8 2+8 2+6 2+8 
191919191919

(1) Bongo Cat has a limited range. To be correct, your Row 3 would be -2+8 -2+8 -2+8 -2+8 -2+6 -2+8. That isn't possible so the better option harmonically is to go to 2+8  instead, as 2 is the minor third of the scale where -2 is the tonic. Also, lose the 1+9 at the end.
(2) Not sure what's happened in your Row 4. Conventionally, chopsticks is in 6/8 time signature whereas you drop in a bar of 3/8 here. Interesting.
(3) Row 7. See (1). Also, best to split this into two rows as this is inconsistent with the approach above of having one row per bar. (4) And lose the final 19.
