### ISSUE TITLE
Baby Shark

### ISSUE THREAD

**Issue by MrClockWork** [Externalizable/bongo.cat#55]
12 666 6666 (X2) 12 666 6666 665

**Comment by wooden-utensil** [comment]
These are meant for issues, not ideas for songs.

**Comment by eduhoribe** [comment]
@wooden-utensil , in the README.md file we have a link to submit our songs, who redirect us to create a issue

**Comment by wooden-utensil** [comment]
> @wooden-utensil , in the README.md file we have a link to submit our songs, who redirect us to create a issue

@eduhoribe Never knew that! Sorry.

**Comment by Chi7519** [comment]
12 8 888888 12 8 888888 887
or
qw i iiiiii qw iiiiiii iiu (Marimba)
is a bit more on key

**Comment by Bbthebest7** [comment]
Nah, I would say to be on key it is 46999999999 4699999999 469999999 998 and them repeat that over and over again.

**Comment by durable-cloud** [comment]
I say it would be 13 6666666 13 6666666 13 6666666 13 6666666 665 and then the previous one. ( 46999999999 4699999999 469999999 998)
