### ISSUE TITLE
Megalovania

### ISSUE THREAD

**Issue by GellertBorsay** [Externalizable/bongo.cat#71]
EE3 0  9 8 6 368
QQ3 0  9 8 6 368
and now we have missing keys after this

**Comment by kalel2909** [comment]
Es mejor usar QQ P O I U Y E Y I

**Comment by kalel2909** [comment]
O en piano 11 0 9 8 7 6 3 6 8

**Comment by Zemtineo** [comment]
quita  la U y el 7... que quede asi:
   
     11 0986368
     QQPOIYEYI
