### ISSUE TITLE
Sounds do not work

### ISSUE THREAD

**Issue by RogerPanza** [Externalizable/bongo.cat#93]
Hi, I downloaded the entire code, and every file to play with this offline, but when I play the piano, or other things, there is no sound. Any help? @Externalizable

**Comment by Externalizable** [comment]
Sorry for getting back to you so late!

You're probably running into [CORS policy violations](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) because your browser is attempting to load the sound files via the `file` protocol scheme.
